### ISSUE TITLE
error at "asyncLoader.configure(app);"

### ISSUE THREAD

**Issue by mybbcat** [subchen/angular-async-loader#1]
Throw error at "asyncLoader.configure(app);"

Uncaught TypeError: Cannot read property 'configure' of undefined 

How to fix?
thanks!

**Comment by subchen** [comment]
Did you add following code? Seem `asyncLoader` is `undefined`.

```
var asyncLoader = require('angular-async-loader');
```

You can see the sample file: https://github.com/subchen/angular-async-loader/blob/master/sample/webapp/app.js#L3

**Comment by mybbcat** [comment]
I have fixed this issue.
use "bower install angular-async-loader" is not work.
must be use "bower install https://github.com/subchen/angular-async-loader.git".

**Comment by subchen** [comment]
Thanks, I added bower install script into README.md
