### ISSUE TITLE
该组件搭配使用RequireJS和单独使用RequireJS有什么区别

### ISSUE THREAD

**Issue by guodidi** [subchen/angular-async-loader#11]
根据我的理解，RequireJS同样也可以完成angular项目中js文件的异步加载(也许也可以说是按需加载)。那么当我使用angularJS+RequireJS+angular-async-loader比单纯使用angularJS+RequireJS有什么更为先进的地方吗？我注意到的一点是，使用了angular-async-loader后，声明函数的方式改变了。
```
define(function (require, exports, module){})
```
而单纯使用RequireJS时声明方式是
```
define(["app"], function(app) {})
```
请问下仅仅是写法上的改变吗？请问可以具体说明一下吗？谢谢

**Comment by subchen** [comment]
requirejs只能加载js文件，并不能将文件内的angular对象注入到angular中。

**Comment by subchen** [comment]
函数的声明方式没有变，requirejs支持amd，cmd等方式，你可以继续用你熟悉的方式
