### ISSUE TITLE
如何实现异步加载angular模块的？

### ISSUE THREAD

**Issue by ystarlongzi** [subchen/angular-async-loader#2]
看了几遍代码，有一点不太明白，希望博主能帮忙解惑下。

在代码[L108-L126行](https://github.com/subchen/angular-async-loader/blob/master/angular-async-loader.js#L108-L126)处定义了一个 `$asyncLoader` 服务，这个服务保存了对 `$controllerProvider`、`$compileProvider`、`$provide`、`$filterProvider` 的引用

而后在代码[L128-L178行](https://github.com/subchen/angular-async-loader/blob/master/angular-async-loader.js#L128-L178)处运行了 `app.run`，修改 `app.value`、`app.constant` 等几个方法，但是感觉这里只是把原来`app`的这些方法，又包装了一下，并没有其它作用，这里博主能解惑下嘛？

**Comment by subchen** [comment]
1.  app.run 无法获取内置的 provider, 需要 $asyncLoader 来中转
2.  app 默认的 value，constant 等几个方法不支持在 angular.bootstrap() 之后进行修改，必须通过 provider 来动态修改。我直接替换默认的方法，这样用户端代码可以不做任何修改就支持动态加载了。

**Comment by ystarlongzi** [comment]
@subchen 
谢谢，我再熟悉下angular的原理。。
