### ISSUE TITLE
有没有办法,按需加载module呢?

### ISSUE THREAD

**Issue by 0x1428571429** [subchen/angular-async-loader#4]
var app = angular.module('app', [
    'ui.router',
    'ngTouch',
    'ngMessages',
    'angular-loading-bar',
    'ngFileUpload',
    'ui.router.breadcrumbs',
    'ngTagsInput'
  ]);

比如说,我现在项目需要依赖这些第三方的module,
但是又不想第一次加载页面,就全部加载一些用不到的module
有没有办法按需加在module?

**Comment by subchen** [comment]
Angular.JS 1.X 没办法按需加载 module，只能一次性加载，第三方的没办法，如果是自己开发module，建议只用一个module，而不是多个module

**Comment by 0x1428571429** [comment]
执行app.bootstrap后,
按照angular的加载方式,确实是很难做到按需加在第三方mudule.
非常感谢,
你的angular-async-loader非常好用,
只需要在路由里添加controllerUrl , dependencies,
使用简单,代码清晰

**Comment by subchen** [comment]
👍
