### ISSUE TITLE
关于exports

### ISSUE THREAD

**Issue by 0x1428571429** [subchen/angular-async-loader#6]
问一个问题,

```
    if (typeof(define) === 'function' && define.amd) {
        define(['angular'], function(angular) {
            return factory(angular);
        });
    } else {
        window.asyncLoader = factory(window.angular);
    }
```

如果找到了define,那便:

```
        define(['angular'], function(angular) {
            return factory(angular);
        });
```

如果用户没有定义 angular的别名为"angular",这样做angular应该会是undefined,
如果在内部调用angular的静态方法,结果肯定会是报错的.

但是window.angular是绝对可以取到angular的.
那为什么还要做一个这样的判断呢?

**Comment by subchen** [comment]
你说的不太对，window.angular 不是绝对能取到的。
为什么这么定义，是因为 javascript 的模块化分为 amd, cmd 等模式。

在 amd 模式下，默认使用 'angular' 作为别名，所以必须定义，而且在amd模式下，window.angular 是默认不输出的。

大部分的 js 模块或者 angular 插件都有类似的代码。

**Comment by 0x1428571429** [comment]
原来是这样,今天在合并js的时候,
或许是文件之间的依赖关系没有写好,导致没有找到angular.所以才来问这个问题,
哈哈听你这么一说,以前倒是没有注意这个问题.
受教了啊...
