### ISSUE TITLE
嵌套views后不能动态加载controler

### ISSUE THREAD

**Issue by wsDever** [subchen/angular-async-loader#8]
router里面如果是：
$stateProvider
            .state("index",{
                url:"/index",
          templateUrl:"tpls/topbar.html",
                                controllerUrl:"js/controls/mainCtrl",
                controller: 'mainRootCtrl'
})
是可以动态加载上mainCtrl.js的，但是如果是用views嵌套之后
$stateProvider
            .state("index",{
                url:"/index",
                views:{
                        '':{
                                            templateUrl:"pub/tpls/index.html",
                            },
                        "topbar@index":{
                                            templateUrl:"tpls/topbar.html",
                                              controllerUrl:"js/controls/mainCtrl.js",
                            controller: 'mainRootCtrl'
                        }
}
mainCtrl.js就不能动态加载上去，导致mainRootCtrl没有定义。
其中index.html中有两个ui-view：
       ui-view="topbar"
       ui-view="menu"
请问这个插件是不支持views里嵌套吗？

**Comment by wsDever** [comment]
其它地方都是照文档所写的，就是加了views嵌套之后就不能动态加载controller的js文件了

卡这里卡几天了，郁闷......

**Comment by subchen** [comment]
嵌入式 views 是支持的： https://github.com/subchen/angular-async-loader/blob/master/angular-async-loader.js#L82-L85

应该是你的代码写错了 `controllerUrl:"js/controls/mainCtrl.js"` 
其中 controllerUrl 不应该以 `.js` 结尾 （`require.js` 会自动加上 `.js` 后缀）

**Comment by wsDever** [comment]
嗯，这个我知道，不是这里的错误（去掉  .js  也是一样的不能加载）

我看了你的源码，也是可以的，但是具体用起来却加载不了，

**Comment by subchen** [comment]
能给出具体的console错误信息吗？

**Comment by wsDever** [comment]
Error: [ng:areq] http://errors.angularjs.org/1.5.8/ng/areq?p0=mainRootCtrl&p1=not%20a%20function%2C%20got%20undefined(…)

$defaultErrorHandler @ angular-ui-router.min.js:347

报上面这个错误，好像是说是mainRootCtrl没有定义。

同时那个view没有加载上去。

**Comment by wsDever** [comment]
另外，如果把
    templateUrl:"tpls/topbar.html",
                        controllerUrl:"js/controls/mainCtrl",
        controller: 'mainRootCtrl'
这里改成

```
templateUrl:"tpls/topbar.html",
```

controllerUrl:"js/controls/mainCtrl",
        controller: ''

就是去掉controller,不会报错，但是对应的view也加不上，

如果把controllerUrl去掉，不报错，view也可以加上，我以前是这样做的，但是controller文件要开始全部加载上去，

**Comment by subchen** [comment]
你可以看一下浏览器的 developer tools 里面的 request logs, 有没有相应的 `tpls/topbar.html` 和 `js/controls/mainCtrl.js` 的下载请求

**Comment by wsDever** [comment]
没有，放在views的外面就有

**Comment by subchen** [comment]
1. 你自己debug一下源码，可以下断点在 https://github.com/subchen/angular-async-loader/blob/master/angular-async-loader.js#L42
2. 把你的app精简一下，做个demo，发给我，我帮你debug一下

**Comment by subchen** [comment]
不好意思，看上去是我错了。

我重新看了一下文档：

```
views

Use the views property to set up multiple views. If you don't need multiple views within a single state 
this property is not needed. Tip: remember that often nested views are more useful and powerful 
than multiple sibling views.

views Object

* keys - {string} name of ui-view
* view config - {object} view configuration object can set up its own [templates] and 
(https://github.com/angular-ui/ui-router/wiki#the-simplest-form-of-state) [controllers].
```

这个 `views` 里面的 `views Object` 不是 `stateConfig`.

```
Then each view in views can set up its own templates (template, templateUrl, templateProvider), 
controllers (controller, controllerProvider).
```

看来只是设置 `template` 和 `controller`, 并不支持 `stateConfig` 的 `resolve`

这样的话，你有2个选择：
1. 把 controllerUrl 移到 state 下面。比如
   
   ``` js
   $stateProvider
   .state("index", {
     url: "/index",
     views: {
       "": {
           templateUrl: "pub/tpls/index.html",
           controller: 'indexCtrl'
       },
       "topbar@index": {
           templateUrl:"tpls/topbar.html",
           controller: 'mainRootCtrl'
       }
     },
     dependencies: [
       "js/controls/indexCtrl",
       "js/controls/mainCtrl"
     ]
   }
   ```
2. 我也可以 fix 一下代码，让 `views` 内部也支持  `controllerUrl` 和 `dependencies`

**Comment by wsDever** [comment]
我把demo精简了一下，放在github了，[这里](https://github.com/wsDever/ngQuestion)，你测试一下这个问题：
运行方法：
npm install
gulp server

测试步骤：
// 在浏览器中分别运行  
            //    /index  和 /default 这个地址
            // 第一个出错,第二个可以正常log 出来
            // 若先执行/default，后执行/index，则正常，因为/default的时候已加载出来了mainCtrl.js

**Comment by wsDever** [comment]
哦，第一种方法也不可以，我之前试过了的

**Comment by subchen** [comment]
好，晚点我试一下

**Comment by subchen** [comment]
第一种方法确实也有问题，我改了一下代码，然后 release 了 1.3.2 版本。
现在 `controllerUrl` 和 `dependencies` 既可以放在 state 下面，也可以放在 views 下面了。

多谢你的测试反馈。
如果还有问题，可以继续开 issue 跟踪。
